version: 1.0.{build}
environment:
  WEBDAV_USER:
    secure: pcgtKyDu4CkpjVJKpFT3Qg==
  WEBDAV_PASSWORD:
    secure: g7p9ERrYqEe4nevMNHlxMw==
build_script:
- cmd: .\build.bat
artifacts:
- path: dist
deploy_script:
- cmd: curl -T dist.zip -u %WEBDAV_USER%:%WEBDAV_PASSWORD% --dump-header - http://webdav.alvisisme.site/gif123